name: Check code quality

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: qualityCheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qualityCheck:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup project'
        uses: ./.github/actions/setup-project
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Build project'
        run: pnpm build

      - name: 'Lint'
        run: pnpm lint

      - name: 'Check missing changesets'
        run: pnpm changeset status --since origin/main

      - name: 'Test'
        run: pnpm test
